-- =========================================================================
-- MIGRATION SCRIPT FINAL: AUTH, RLS, TOKEN ĐỊNH DANH & CẤU HÌNH HỆ THỐNG
-- Dự án: App Chấm Công HSTC (Siêu Thanh Hà Nội)
-- =========================================================================

-- 1. Kích hoạt pgcrypto để băm mật khẩu bảo mật
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Tạo bảng Auth tách biệt mật khẩu cho Admin/TBP (nếu chưa có)
CREATE TABLE IF NOT EXISTS public.chamcong_auth (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL,
    department text,
    updated_at timestamptz DEFAULT now()
);

-- 3. Tạo bảng lưu trữ cấu hình hệ thống (nếu chưa có)
CREATE TABLE IF NOT EXISTS public.chamcong_system_config (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_at timestamptz DEFAULT now()
);

-- 4. Cập nhật bảng nhân viên để áp dụng token định danh chống chấm hộ
ALTER TABLE public.chamcong_employees ADD COLUMN IF NOT EXISTS token uuid UNIQUE DEFAULT gen_random_uuid();

-- 5. Tắt tạm RLS trong quá trình Migration để tránh lỗi
ALTER TABLE public.chamcong_attendance_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_attendance_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_holidays DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_shift_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_system_config DISABLE ROW LEVEL SECURITY;

-- 6. Chuẩn hóa dữ liệu trạng thái nhân viên và token
UPDATE public.chamcong_employees
SET status = 'Đang làm việc'
WHERE status IN ('active', 'đang làm', 'Đang làm việc');

UPDATE public.chamcong_employees
SET status = 'Đã nghỉ việc'
WHERE status NOT IN ('Đang làm việc');

UPDATE public.chamcong_employees SET token = gen_random_uuid() WHERE token IS NULL;

-- Khởi tạo tài khoản mặc định trong chamcong_auth
INSERT INTO public.chamcong_auth (username, password_hash, role, department)
VALUES
('admin', crypt('admin_kt2026', gen_salt('bf')), 'admin', null),
('tbp_kd', crypt('tbp_kd2026', gen_salt('bf')), 'TBP', 'Kinh doanh'),
('tbp_kt', crypt('tbp_kt2026', gen_salt('bf')), 'TBP', 'Kế toán-Hành chính')
ON CONFLICT (username) DO NOTHING;

-- Khởi tạo cấu hình hệ thống mặc định nếu chưa có
INSERT INTO public.chamcong_system_config (key, value) VALUES
('company_name', 'CHẤM CÔNG CBNV'),
('office_name', 'Siêu Thanh Hà Nội'),
('company_address', 'Số 5 Nguyễn Ngọc Vũ, Phường Thanh Xuân, TP Hà Nội'),
('office_lat', '21.00861322599807'),
('office_lng', '105.81294998643875'),
('office_radius', '200'),
('max_distance', '15000'),
('allow_holiday', 'false'),
('allow_multiple', 'false')
ON CONFLICT (key) DO NOTHING;

-- 7. Tạo hàm RPC xác thực đăng nhập bảo mật trong PostgreSQL (dành cho Edge Function)
CREATE OR REPLACE FUNCTION public.chamcong_verify_auth(p_username text, p_password text)
RETURNS TABLE (id int, username text, role text, department text) AS $$
BEGIN
  RETURN QUERY
  SELECT a.id, a.username, a.role, a.department
  FROM public.chamcong_auth a
  WHERE a.username = p_username AND a.password_hash = crypt(p_password, a.password_hash);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Hàm RPC xác thực chỉ dùng mật khẩu (dành cho trang TBP)
CREATE OR REPLACE FUNCTION public.chamcong_verify_auth_password_only(p_password text)
RETURNS TABLE (id int, username text, role text, department text) AS $$
BEGIN
  RETURN QUERY
  SELECT a.id, a.username, a.role, a.department
  FROM public.chamcong_auth a
  WHERE a.password_hash = crypt(p_password, a.password_hash);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Hàm RPC cập nhật mật khẩu băm bảo mật
CREATE OR REPLACE FUNCTION public.chamcong_update_password(p_username text, p_password text)
RETURNS boolean AS $$
BEGIN
  UPDATE public.chamcong_auth
  SET password_hash = crypt(p_password, gen_salt('bf')),
      updated_at = now()
  WHERE username = p_username;
  RETURN FOUND;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. KÍCH HOẠT LẠI RLS (Row Level Security) - Deny Public
ALTER TABLE public.chamcong_attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_shift_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamcong_system_config ENABLE ROW LEVEL SECURITY;

-- 9. Xoá bỏ các Policies cũ nếu có (tránh xung đột hay lỗi already exists)
DROP POLICY IF EXISTS "Public Select Logs" ON public.chamcong_attendance_logs;
DROP POLICY IF EXISTS "Public Insert Logs" ON public.chamcong_attendance_logs;
DROP POLICY IF EXISTS "Public Select Records" ON public.chamcong_attendance_records;
DROP POLICY IF EXISTS "Public Insert Records" ON public.chamcong_attendance_records;
DROP POLICY IF EXISTS "Public Update Records" ON public.chamcong_attendance_records;
DROP POLICY IF EXISTS "Public Select Employees" ON public.chamcong_employees;
DROP POLICY IF EXISTS "Cho phép xem records qua JWT" ON public.chamcong_attendance_records;
DROP POLICY IF EXISTS "Cho phép Admin/TBP xem employees" ON public.chamcong_employees;
DROP POLICY IF EXISTS "Admin xem Logs" ON public.chamcong_attendance_logs;
DROP POLICY IF EXISTS "Mọi user auth được đọc shift_config" ON public.chamcong_shift_config;
DROP POLICY IF EXISTS "Mọi user auth được đọc holidays" ON public.chamcong_holidays;
DROP POLICY IF EXISTS "Mọi user auth được đọc guide" ON public.chamcong_guide_content;
DROP POLICY IF EXISTS "Mọi user auth được đọc settings" ON public.chamcong_admin_settings;
DROP POLICY IF EXISTS "Mọi user auth được đọc system_config" ON public.chamcong_system_config;

-- 10. Tạo Policies mới: CHỈ CHO PHÉP XEM (SELECT) theo JWT
-- Bảng Attendance Records: CBNV được xem lịch sử của mình, Admin/TBP được xem tất cả
CREATE POLICY "Cho phép xem records qua JWT" ON public.chamcong_attendance_records
FOR SELECT TO authenticated
USING (
  (auth.jwt() -> 'user_metadata' ->> 'type' = 'cbnv' AND employee_name = auth.jwt() -> 'user_metadata' ->> 'employee_name')
  OR
  (auth.jwt() -> 'user_metadata' ->> 'type' = 'admin')
);

-- Bảng Employees: TBP/Admin được xem toàn bộ; CBNV chỉ xem thông tin mình
CREATE POLICY "Cho phép Admin/TBP xem employees" ON public.chamcong_employees
FOR SELECT TO authenticated
USING (
  (auth.jwt() -> 'user_metadata' ->> 'type' = 'admin')
  OR
  (auth.jwt() -> 'user_metadata' ->> 'type' = 'cbnv' AND name = auth.jwt() -> 'user_metadata' ->> 'employee_name')
);

-- Bảng Attendance Logs: Chỉ Admin được xem raw logs
CREATE POLICY "Admin xem Logs" ON public.chamcong_attendance_logs
FOR SELECT TO authenticated
USING (auth.jwt() -> 'user_metadata' ->> 'type' = 'admin' AND auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');

-- Bảng cấu hình và ngày lễ: Mọi user đã auth (CBNV, Admin) đều được tải cài đặt
CREATE POLICY "Mọi user auth được đọc shift_config" ON public.chamcong_shift_config FOR SELECT TO authenticated USING (true);
CREATE POLICY "Mọi user auth được đọc holidays" ON public.chamcong_holidays FOR SELECT TO authenticated USING (true);
CREATE POLICY "Mọi user auth được đọc guide" ON public.chamcong_guide_content FOR SELECT TO authenticated USING (true);
CREATE POLICY "Mọi user auth được đọc settings" ON public.chamcong_admin_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Mọi user auth được đọc system_config" ON public.chamcong_system_config FOR SELECT TO authenticated USING (true);

-- GHI CHÚ: TẤT CẢ QUYỀN INSERT / UPDATE / DELETE ĐỀU BỊ KHÓA (KHÔNG CÓ POLICY)
-- Mọi thao tác ghi phải thông qua Deno Edge Function sử dụng Service Role Key (bỏ qua RLS)!
